name: Section 2 Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  
      - name: Install dependencies
        run: pip install -r requirements.txt
  pre_commit_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Install pre-commit
        run: |
         apt-get update
         apt-get install -y --no-install-recommends git
         pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files      